name: Test

on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v4
            with:
              python-version: '3.9'
              # cache: pip
              # [**/requirements.txt or **/pyproject.toml], make sure you have checked out the target repository
          - run: pip install -e .
            working-directory: "chapter4"
          - run: pytest ./tests -v
            working-directory: "chapter4"
