name: Annotation

on: push

jobs:
    annotation:
        runs-on: ubuntu-latest
        steps:
            - run: echo "::error::This is a error"
            - run: echo "::warning::This is a warning"
            - run: echo "::notice::This is a notice"