name: Matrix

on: push

jobs:
    print:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{matrix}}
        steps:
            - run: echo "${RUNNER_OS}"
              shell: bash