name: Share

on: push

jobs:
    github-output:
        runs-on: ubuntu-latest
        steps:
            - id: source
              run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
            - env:
                RESULT: ${{steps.source.outputs.result}}
              run: echo "${RESULT}"

    github-env:
        runs-on: ubuntu-latest
        steps:
            - run: echo "RESULT=Hello" >> "${GITHUB_ENV}"
            - run: echo "${RESULT}"
